dataset:
  dataset_name: Amazon-ratings
subgraph:
  num_subgraphs: 10
  delta: 20
  train_ratio: 0.1
  test_ratio: 0.8
  partitioning: random
  prune: False
  pruning_th: 30
model:
  num_samples: [5, 10]
  batch: False
  batch_size: 64
  local_epochs: 1
  lr: 0.002
  weight_decay: 0.0002
  dropout: 0.7
  gnn_layer_type: sage
  smodel_type: DGCN   # GNN, DGCN
  fmodel_type: same   #GNN, DGCN, same
  iterations: 70
  metric: acc
feature_model:
  gnn_layer_sizes: [256,256,128]
  DGCN_layer_sizes: [64]
  mlp_layer_sizes: [64]
  DGCN_layers: 2
structure_model:
  GNN_structure_layers_sizes: [128, 64]
  DGCN_structure_layers_size: [256]
  DGCN_layers: 5
  # structure_type: degree
  # structure_type: GDV
  structure_type: hop2vec
  # structure_type: node2vec
  num_structural_features: 256
  estimate: False
  num_mp_vectors: 10
  rw_len: 50
  gnn_epochs: 500
  mlp_epochs: 200
node2vec:
  epochs: 50
  walk_length: 20
  context_size: 10
  walks_per_node: 10
  lr: 0.01
  batch_size: 128
  num_negative_samples: 1
  p: 1
  q: 1
  show_bar: True
fedsage:
  neighgen_epochs: 30
  neighgen_lr: 0.002
  neighen_feature_gen: [256, 2048]
  num_pred: 5
  latent_dim: 128
  hidden_layer_sizes: [32]
  impaired_train_nodes_ratio: 0.6
  impaired_test_nodes_ratio: 0.2
  hidden_portion: 0.5
  use_inter_connections: False
  a: 1
  b: 1
  c: 1
fedpub:
  epochs: 50
  frac: 1.0
  clsf_mask_one: True
  laye_mask_one: True
  norm_scale: 3
  min_lr: 0.0001
  momentum_opt: 0.9
  lr: 0.001
  weight_decay: 0.000001
  warmup_epochs: 10
  base_momentum: 0.99
  final_momentum: 1.0
  n_dims: 128
  agg_norm: exp
  n_proxy: 5
  l1: 0.001
  loc_l2: 0.001

